// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkvwu5DE1iTtkZ2-58wrdsYK1EIoX4qgM',
    appId: '1:787338406801:web:8c8b2e175254d3c25f0830',
    messagingSenderId: '787338406801',
    projectId: 'tableverse-36be6',
    authDomain: 'tableverse-36be6.firebaseapp.com',
    storageBucket: 'tableverse-36be6.firebasestorage.app',
    measurementId: 'G-61WLESZP9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlwi-jOwHOD5ybePgSTLzFgYNZ60N4ewo',
    appId: '1:787338406801:android:ce78a9c24b240a5d5f0830',
    messagingSenderId: '787338406801',
    projectId: 'tableverse-36be6',
    storageBucket: 'tableverse-36be6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgnENIj3rUUhkTETYMWUSTZZxZW_PNgqY',
    appId: '1:787338406801:ios:cb5b05ace15af86e5f0830',
    messagingSenderId: '787338406801',
    projectId: 'tableverse-36be6',
    storageBucket: 'tableverse-36be6.firebasestorage.app',
    iosBundleId: 'com.example.tableverse',
  );
}
